### ISSUE TITLE
Table list overflowing: add scroll bar?

### ISSUE THREAD

**Issue by frankvollebregt** [Chimerapps/moor_inspector#15]
Thanks for this plugin, it's very useful!

My data model is quite large (>60 tables). Currently, when I look through the list of tables, the only way to reach the ones towards the bottom is to enlarge the Drift Inspector tool window (and even then, at full height on my 1440p screen I cannot access the last ones).

Would it be possible to add a scroll bar to the table list, so that I can more easily find all of my tables?

**Comment by NicolaVerbeeck** [comment]
Hey @frankvollebregt, good suggestion, I will be retiring this plugin soon though. It is being replaced with a more advanced one that integrates all kinds of local storage and a better query editor/system.
Please take a look here: https://pub.dev/packages/drift_local_storage_inspector and here https://pub.dev/packages/storage_inspector

The plugin can be found at https://plugins.jetbrains.com/plugin/18231-local-storage-inspector/versions

Note that not everything is supported in database mode yet (editing most of all), the plugin is under active development and will replace this one when it is finished.

**Comment by NicolaVerbeeck** [comment]
I just noticed I am missing a scroll component there as well 😅 It will be there in the next release sometime this week I hope

**Comment by frankvollebregt** [comment]
Good to hear, thank you! I'll switch over to the new plugin then

**Comment by NicolaVerbeeck** [comment]
@frankvollebregt how is the new plugin working for you? Any feedback is always welcome (perhaps on that repository issue tracker)
