### ISSUE TITLE
UI: Disconnect does not remove the db tables/columns

### ISSUE THREAD

**Issue by vanlooverenkoen** [Chimerapps/moor_inspector#5]
When you:

- stop (from ui)
- disconnect after a hot restart
- Restore default layout (from ui)

The ui will change to disconnected. Play button will be enabled. stop button disabled.

But the tables & columns are still visible. This is confusing

**Comment by NicolaVerbeeck** [comment]
This makes sense, you can still inspect the data we received before the disconnect (could be caused by a crash, ...)
