### ISSUE TITLE
How to configure the plugin?

### ISSUE THREAD

**Issue by andreag85** [Chimerapps/moor_inspector#9]
I'm trying to use moor_inspector but I got the issue in the attached screenshot.
I have adb installed and fully working.

The code I use is the following
`Future<void> initMoorInspector(Appdatabase appdatabase) async {
  final moorInspectorBuilder = MoorInspectorBuilder()
    ..bundleId = EnvironmentConfig.APP_ID
    ..icon = 'flutter'
    ..port = 8085
    ..addDatabase('db', appdatabase);
  final inspector = moorInspectorBuilder.build();

  //Start server and announcement server
  await inspector.start();
}`
and I tried both setting port and none.

![Schermata 2021-01-04 alle 11 29 12](https://user-images.githubusercontent.com/2011256/103525876-411afc00-4e80-11eb-94ba-d85e0c39573c.png)

**Comment by NicolaVerbeeck** [comment]
To use automatic detection you should use port 0 (which is the default). Also in your screenshot I can see the warnings in the dialog: the plugin cannot locate your adb and libimobiledevice binaries. You can set them in the general android studio/intellij preferences.

**Comment by NicolaVerbeeck** [comment]
Example: 
<img width="899" alt="Config" src="https://user-images.githubusercontent.com/7778415/103531162-11242680-4e89-11eb-843f-34a382471417.png">
